Add registration screen and API call
nibble-lumen/washere-frontend pull request #11
Opened 2021-03-20 17:09 UTC by aldin-alagic

2021-03-20 20:09 UTC, fifi98 commented
If I try to register with an existing email or username, I will be taken to the welcome screen with "There was a problem with your request. Please try again later. Request failed with status code 400" message. We need to inform the user that the entered email/username is taken without he needing to start the registration process all over again from the welcome screen.

2021-03-21 19:44 UTC, fobos531 commented
> If I try to register with an existing email or username, I will be taken to the welcome screen with "There was a problem with your request. Please try again later. Request failed with status code 400" message. We need to inform the user that the entered email/username is taken without he needing to start the registration process all over again from the welcome screen.

This will be added when [PR#10](https://github.com/nibble-lumen/washere-frontend/pull/10) is merged, see commit: https://github.com/nibble-lumen/washere-frontend/pull/10/commits/8c9fe9b99391ebfcaded7b406cdc52a00c38b859

2021-03-21 21:10 UTC, fobos531 requested changes

2021-03-21 21:10 UTC, fobos531 commented on WasHere/src/screens/Register.js
> +              <FormField autoCorrect={false} icon="desktop-outline" name="username" placeholder="Username" />
I would set `autoCapitalize` to `"none"` here as well.

2021-03-21 21:10 UTC, fobos531 commented on WasHere/src/screens/Register.js
> +      "Password must contain at least 8 characters, one uppercase, one number and one special case character",
The word `case` is redundant here.

2021-03-21 21:10 UTC, fobos531 commented on WasHere/src/screens/Register.js
> +    navigation.navigate(routes.WELCOME)
Is it a good idea to automatically navigate to Welcome route here? What happens if the frontend sends an API call, but the backend for whatever reason returns a 4xx response. The approach I would take here is an additional field in auth state, which keeps track of whether the registration was successful. If it was, only then should the user be navigated back to Welcome screen. See this commit for reference: https://github.com/nibble-lumen/washere-frontend/pull/10/commits/093d86a8a36a0207c663b829d5237ed995f10668

Also, when [PR#10](https://github.com/nibble-lumen/washere-frontend/pull/10) is merged, feel free to make use of `react-native-flash-message` library, as demonstrated in commit linked above.

2021-03-28 23:12 UTC, aldin-alagic commented on WasHere/src/screens/Register.js
> +    navigation.navigate(routes.WELCOME)
"The approach I would take here is an additional field in auth state, which keeps track of whether the registration was successful. " That field exists and it's called apiResult.success

2021-03-31 10:09 UTC, merged